/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as RunnersRouteImport } from './routes/runners'
import { Route as ScratchpadsRouteImport } from './routes/scratchpads'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'
import { Route as ScratchpadsIdRouteImport } from './routes/scratchpads_.$id'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as TodosIdRouteImport } from './routes/todos_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnersRoute = RunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchpadsRoute = ScratchpadsRouteImport.update({
  id: '/scratchpads',
  path: '/scratchpads',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScratchpadsIdRoute = ScratchpadsIdRouteImport.update({
  id: '/scratchpads_/$id',
  path: '/scratchpads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdRoute = TodosIdRouteImport.update({
  id: '/todos_/$id',
  path: '/todos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/memories': typeof MemoriesRoute
  '/runners': typeof RunnersRoute
  '/scratchpads': typeof ScratchpadsRoute
  '/sessions': typeof SessionsRoute
  '/todos': typeof TodosRoute
  '/chats/$id': typeof ChatsIdRoute
  '/scratchpads/$id': typeof ScratchpadsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/todos/$id': typeof TodosIdRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/memories': typeof MemoriesRoute
  '/runners': typeof RunnersRoute
  '/scratchpads': typeof ScratchpadsRoute
  '/sessions': typeof SessionsRoute
  '/todos': typeof TodosRoute
  '/chats/$id': typeof ChatsIdRoute
  '/scratchpads/$id': typeof ScratchpadsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/todos/$id': typeof TodosIdRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/memories': typeof MemoriesRoute
  '/runners': typeof RunnersRoute
  '/scratchpads': typeof ScratchpadsRoute
  '/sessions': typeof SessionsRoute
  '/todos': typeof TodosRoute
  '/chats/$id': typeof ChatsIdRoute
  '/scratchpads_/$id': typeof ScratchpadsIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/todos_/$id': typeof TodosIdRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/memories'
    | '/runners'
    | '/scratchpads'
    | '/sessions'
    | '/todos'
    | '/chats/$id'
    | '/scratchpads/$id'
    | '/tasks/$id'
    | '/todos/$id'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/memories'
    | '/runners'
    | '/scratchpads'
    | '/sessions'
    | '/todos'
    | '/chats/$id'
    | '/scratchpads/$id'
    | '/tasks/$id'
    | '/todos/$id'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/memories'
    | '/runners'
    | '/scratchpads'
    | '/sessions'
    | '/todos'
    | '/chats/$id'
    | '/scratchpads_/$id'
    | '/tasks/$id'
    | '/todos_/$id'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  MemoriesRoute: typeof MemoriesRoute
  RunnersRoute: typeof RunnersRoute
  ScratchpadsRoute: typeof ScratchpadsRoute
  SessionsRoute: typeof SessionsRoute
  TodosRoute: typeof TodosRoute
  ChatsIdRoute: typeof ChatsIdRoute
  ScratchpadsIdRoute: typeof ScratchpadsIdRoute
  TasksIdRoute: typeof TasksIdRoute
  TodosIdRoute: typeof TodosIdRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runners': {
      id: '/runners'
      path: '/runners'
      fullPath: '/runners'
      preLoaderRoute: typeof RunnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratchpads': {
      id: '/scratchpads'
      path: '/scratchpads'
      fullPath: '/scratchpads'
      preLoaderRoute: typeof ScratchpadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scratchpads_/$id': {
      id: '/scratchpads_/$id'
      path: '/scratchpads/$id'
      fullPath: '/scratchpads/$id'
      preLoaderRoute: typeof ScratchpadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos_/$id': {
      id: '/todos_/$id'
      path: '/todos/$id'
      fullPath: '/todos/$id'
      preLoaderRoute: typeof TodosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  MemoriesRoute: MemoriesRoute,
  RunnersRoute: RunnersRoute,
  ScratchpadsRoute: ScratchpadsRoute,
  SessionsRoute: SessionsRoute,
  TodosRoute: TodosRoute,
  ChatsIdRoute: ChatsIdRoute,
  ScratchpadsIdRoute: ScratchpadsIdRoute,
  TasksIdRoute: TasksIdRoute,
  TodosIdRoute: TodosIdRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
